# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 18:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dmdashboard', '0003_auto_20170615_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='party',
            unique_together=set([('dm', 'name')]),
        ),
    ]
