# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmdashboard', '0004_auto_20170615_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='alignment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='armor_class',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='background',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='char_class',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='name',
            field=models.TextField(default='Thimble'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='passive_perception',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='spell_dc',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='name',
            field=models.TextField(),
        ),
    ]
