# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmdashboard', '0006_auto_20170615_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
