# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmdashboard', '0007_party_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='slug',
            field=models.TextField(blank=True),
        ),
    ]
