# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 19:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dmdashboard', '0008_party_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='party',
            unique_together=set([('dm', 'slug')]),
        ),
    ]
