# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmdashboard', '0009_auto_20170620_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='slug',
            field=models.TextField(blank=True),
        ),
    ]
