# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-02 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmdashboard', '0012_auto_20180802_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='name',
            field=models.TextField(),
        ),
    ]
